preferred_syntax = :sass
http_path = '/'
css_dir = 'app/css'
sass_dir = 'app/sass'
images_dir = 'app/images'
javascripts_dir = 'app/js'
relative_assets = true
line_comments = true
# output_style = :compressed