preferred_syntax = :sass
http_path = '/'
css_dir = 'app/assets/styles'
sass_dir = 'app/assets/styles'
images_dir = 'app/assets/images'
javascripts_dir = 'app/assets/scripts'
relative_assets = true
line_comments = true
# output_style = :compressed